"C:\Program Files\IronPython 2.7\ipy.exe" "C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_pytest_runner.py" --target test_something.py::test_something
Testing started at 21:13 ...
Launching py.test with arguments test_something.py::test_something in C:\test\ironpython_training
============================= test session starts ==============================
platform cli -- Python 2.7.5 -- py-1.4.26 -- pytest-2.7.0
rootdir: C:\test\ironpython_training, inifile: pytest.ini


:None ()
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\pytest_plugin.py:255: in pytest_collectreport
    self.report_test_failure(test_id, report)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\pytest_plugin.py:196: in report_test_failure
    self.teamcity.testFailed(test_id, message, str(report.longrepr), flowId=test_id)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_runner_tools.py:273: in testFailed
    self.message("testFailed", **args)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_runner_tools.py:200: in message
    _old_service_messages.message(self, messageName, **properties)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\messages.py:72: in message
    message += (" %s='%s'" % (k, self.escapeValue(value)))
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\messages.py:54: in escapeValue
    return escape_value(self.encode(value))
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\messages.py:44: in encode
    value = value.encode(self.encoding)
E   UnicodeEncodeError: ('unknown', u'\xd0', 102, 103, u'\u041d\u0435 \u0443\u0434\u0430\u0435\u0442\u0441\u044f \u043f\u0440\u0435\u043e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u0442\u044c \u0441\u0438\u043c\u0432\u043e\u043b \u042e\u043d\u0438\u043a\u043e\u0434\u0430 \\u00D0 \u043f\u043e \u0438\u043d\u0434\u0435\u043a\u0441\u0443 102 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442 \u0437\u0430\u0434\u0430\u043d\u043d\u043e\u0439 \u043a\u043e\u0434\u043e\u0432\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b.')
collected 0 items / 2 errors

==================================== ERRORS ====================================
______________________ ERROR collecting test_something.py ______________________
test_something.py:7: in <module>
    clr.AddReferenceByName('TestStack.White')
E   IOError: [Errno 2] �� 㤠���� ����㧨�� 䠩� ��� ᡮ�� "TestStack.White" ���� ���� �� �� ����ᨬ��⥩. �� 㤠���� ���� 㪠����� 䠩�.
______________________________ ERROR collecting  _______________________________
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\pytest_plugin.py:255: in pytest_collectreport
    self.report_test_failure(test_id, report)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\pytest_plugin.py:196: in report_test_failure
    self.teamcity.testFailed(test_id, message, str(report.longrepr), flowId=test_id)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_runner_tools.py:273: in testFailed
    self.message("testFailed", **args)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\_jb_runner_tools.py:200: in message
    _old_service_messages.message(self, messageName, **properties)
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\messages.py:72: in message
    message += (" %s='%s'" % (k, self.escapeValue(value)))
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\messages.py:54: in escapeValue
    return escape_value(self.encode(value))
C:\Program Files\JetBrains\PyCharm Community Edition 2017.1.3\helpers\pycharm\teamcity\messages.py:44: in encode
    value = value.encode(self.encoding)
E   UnicodeEncodeError: ('unknown', u'\xd0', 102, 103, u'\u041d\u0435 \u0443\u0434\u0430\u0435\u0442\u0441\u044f \u043f\u0440\u0435\u043e\u0431\u0440\u0430\u0437\u043e\u0432\u0430\u0442\u044c \u0441\u0438\u043c\u0432\u043e\u043b \u042e\u043d\u0438\u043a\u043e\u0434\u0430 \\u00D0 \u043f\u043e \u0438\u043d\u0434\u0435\u043a\u0441\u0443 102 \u0432 \u0444\u043e\u0440\u043c\u0430\u0442 \u0437\u0430\u0434\u0430\u043d\u043d\u043e\u0439 \u043a\u043e\u0434\u043e\u0432\u043e\u0439 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b.')
=========================== 2 error in 1.19 seconds ============================

Process finished with exit code 0
